bot_0:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/karvinoir_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  row_range: [366, 375]

bot_1:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql0_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  row_range: [356, 365]

bot_2:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/alexanderborchun_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  row_range: [346, 355]

bot_3:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/karvinior_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  row_range: [336, 345]

bot_4:
  project: hypos_norm
  subproject: gen
  site: perplexity
  mode: grok
  model: perplexity_grok
  browser_master_profile: ~/bot_master_profile 
  roi: [0, 1242, 500, 620]
  cooldown: 1.0
  row_range: [336, 340]

bot_5:
  project: hypos_norm
  subproject: gen
  site: perplexity
  mode: grok
  model: perplexity_grok
  browser_master_profile: ~/bot_master_profile 
  roi: [501, 1242, 500, 620]
  cooldown: 1.0
  row_range: [341, 345]

bot_6:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  browser_master_profile: ~/bot_master_profile 
  roi: [2505, 30, 500, 620]
  cooldown: 1.0
  row_range: [346, 350]

bot_11:
  project: hypos_norm
  subproject: gen
  site: gpt
  mode: study_learn
  model: gpt
  browser_master_profile: ~/bot_master_profile 
  roi: [0, 621, 500, 620]
  cooldown: 1.0
  row_range: [0, 100]

bot_10:
  project: hypos_norm
  subproject: gen
  site: perplexity
  mode: grok
  model: perplexity_grok
  scenario: grok
  browser_master_profile: ~/bot_master_profile 
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  row_range: [124, 148]

bot_12:
  project: hypos_norm
  subproject: gen
  site: perplexity
  mode: grok
  model: perplexity_grok
  browser_master_profile: ~/bot_master_profile 
  roi: [0, 621, 500, 620]
  cooldown: 1.0
  row_range: [163, 189]