bot_0_:
  project: hypos_norm
  subproject: gen
  site: gemini
  mode: thinking
  model: gemini
  scenario: thinking
  browser_master_profile: ~/vanthuan1990t@gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 280.0
  row_range: [600, 799]
  max_questions: 200
  restart_delay: None
  proxy: [186.65.122.102, 8000, "bbaBmV", "vEyoqs"]
  schedule:
    start_immediately: true
    start_times:
      - "00:00"
      - "06:00"
      - "12:00"
      - "18:00"

bot_0:
  project: hypos_norm
  subproject: gen
  site: gpt
  mode: web_search
  model: gpt
  scenario: web_search
  browser_master_profile: ~/rxmzge8117@outlook.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 240.0
  row_range: [125, 144]
  max_questions: 200
  restart_delay: None
  proxy: [186.65.122.102, 8000, bbaBmV, vEyoqs]
  schedule:
    start_immediately: true
    start_times:
      - "00:00"
      - "06:00"
      - "12:00"
      - "18:00"
  subscription: gpt_go

bot_1:
  project: hypos_norm
  subproject: gen
  site: gpt
  mode: web_search
  model: gpt
  scenario: web_search
  browser_master_profile: ~/halseycusenza35@outlook.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 90.0
  row_range: [145, 199]
  max_questions: 200
  restart_delay: None
  proxy: [186.65.122.102, 8000, bbaBmV, vEyoqs]
  schedule:
    start_immediately: true
    start_times:
      - "00:00"
      - "06:00"
      - "12:00"
      - "18:00"
  subscription: gpt_plus

bot_2:
  project: hypos_norm
  subproject: gen
  site: claude
  mode: pro
  model: gemini
  scenario: pro
  browser_master_profile: ~/leinswdolenfnk4@outlook.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 1800
  row_range: [296, 500]
  max_questions: 100
  restart_delay: None
  proxy: [186.65.122.102, 8000, bbaBmV, vEyoqs]
  schedule:
    start_immediately: true
    start_times:
      - "00:00"
      - "06:00"
      - "12:00"
      - "18:00"

bot_3:
  project: hypos_norm
  subproject: gen
  site: gemini
  mode: pro
  model: gemini
  scenario: pro
  browser_master_profile: ~/vanthuan1990t@gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 5.0
  row_range: [225, 299]
  max_questions: 100
  restart_delay: 3600
  proxy: [186.65.122.102, 8000]
  schedule:
    start_immediately: true
    start_times:
      - "00:00"
      - "06:00"
      - "12:00"
      - "18:00"

bot_0_:
  project: hypos_norm
  subproject: gen
  site: gpt
  mode: web_search
  model: gpt
  scenario: web_search
  browser_master_profile: ~/rxmzge8117_outlook.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 5.0
  row_range: [0, 40]
  max_questions: 40
  restart_delay: 3600
  proxy: [186.65.122.102, 8000]

bot_0_:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/karvinoir_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 5.0
  row_range: [676, 700]
  max_questions: 100
  restart_delay: 180

bot_1_:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql0_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 5.0
  row_range: [701, 725]
  max_questions: 100
  restart_delay: 180

bot_2_:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/alexanderborchun_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 5.0
  row_range: [726, 750]
  max_questions: 100
  restart_delay: 180

bot_3_:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/karvinior_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 5.0
  row_range: [751, 775]
  max_questions: 100
  restart_delay: 3600

bot_4:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/rxmzge8117_outlook.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 5.0
  row_range: [776, 800]
  max_questions: 100
  restart_delay: 3600

bot_5:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 5.0
  row_range: [801, 825]
  max_questions: 100
  restart_delay: 3600

bot_6:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 5.0
  row_range: [516, 525]
  max_questions: 100
  restart_delay: 3600

bot_7:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 5.0
  row_range: [516, 525]
  max_questions: 100
  restart_delay: 3600

bot_8:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 5.0
  row_range: [516, 525]
  max_questions: 100
  restart_delay: 3600

bot_9:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 5.0
  row_range: [516, 525]
  max_questions: 100
  restart_delay: 3600

bot_10:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 5.0
  row_range: [516, 525]
  max_questions: 100
  restart_delay: 3600

bot_11:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 5.0
  row_range: [516, 525]
  max_questions: 100
  restart_delay: 3600

bot_12:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 5.0
  row_range: [516, 525]
  max_questions: 100
  restart_delay: 3600

bot_13:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 5.0
  row_range: [516, 525]
  max_questions: 100
  restart_delay: 3600

bot_14:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 5.0
  row_range: [516, 525]
  max_questions: 100
  restart_delay: 3600

bot_15:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 5.0
  row_range: [516, 525]
  max_questions: 100
  restart_delay: 3600

bot_16:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 5.0
  row_range: [516, 525]
  max_questions: 100
  restart_delay: 3600

bot_17:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 5.0
  row_range: [516, 525]
  max_questions: 100
  restart_delay: 3600

bot_18:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 5.0
  row_range: [516, 525]
  max_questions: 100
  restart_delay: 3600

bot_19:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 5.0
  row_range: [516, 525]
  max_questions: 100
  restart_delay: 3600


bot_20:
  project: hypos_norm
  subproject: gen
  site: gpt
  mode: study_learn
  model: gpt
  browser_master_profile: ~/bot_master_profile
  roi: [0, 621, 500, 620]
  cooldown: 1.0
  question_interval: 5.0
  row_range: [0, 100]
  max_questions: 100
  restart_delay: 3600

bot_21:
  project: hypos_norm
  subproject: gen
  site: perplexity
  mode: grok
  model: perplexity_grok
  scenario: grok
  browser_master_profile: ~/bot_master_profile
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 5.0
  row_range: [124, 148]
  max_questions: 100
  restart_delay: 3600

bot_22:
  project: hypos_norm
  subproject: gen
  site: perplexity
  mode: grok
  model: perplexity_grok
  browser_master_profile: ~/bot_master_profile
  roi: [0, 621, 500, 620]
  cooldown: 1.0
  question_interval: 5.0
  row_range: [163, 189]
  max_questions: 100
  restart_delay: 3600