bot_0:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/karvinoir_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  row_range: [527, 551]

bot_1:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql0_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  row_range: [552, 575]

bot_2:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/alexanderborchun_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  row_range: [576, 600]

bot_3:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/karvinior_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  row_range: [601, 625]

bot_4:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/rxmzge8117_outlook.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  row_range: [626, 650]

bot_5:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  row_range: [651, 675]

bot_6:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  row_range: [516, 525]

bot_7:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  row_range: [516, 525]

bot_8:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  row_range: [516, 525]

bot_9:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  row_range: [516, 525]

bot_10:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  row_range: [516, 525]

bot_11:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  row_range: [516, 525]

bot_12:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  row_range: [516, 525]

bot_13:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  row_range: [516, 525]

bot_14:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  row_range: [516, 525]

bot_15:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  row_range: [516, 525]

bot_16:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  row_range: [516, 525]

bot_17:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  row_range: [516, 525]

bot_18:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  row_range: [516, 525]

bot_19:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql_gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  row_range: [516, 525]


bot_20:
  project: hypos_norm
  subproject: gen
  site: gpt
  mode: study_learn
  model: gpt
  browser_master_profile: ~/bot_master_profile 
  roi: [0, 621, 500, 620]
  cooldown: 1.0
  row_range: [0, 100]

bot_21:
  project: hypos_norm
  subproject: gen
  site: perplexity
  mode: grok
  model: perplexity_grok
  scenario: grok
  browser_master_profile: ~/bot_master_profile 
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  row_range: [124, 148]

bot_22:
  project: hypos_norm
  subproject: gen
  site: perplexity
  mode: grok
  model: perplexity_grok
  browser_master_profile: ~/bot_master_profile 
  roi: [0, 621, 500, 620]
  cooldown: 1.0
  row_range: [163, 189]